stateDiagram-v2
    direction LR
    Requirements --> Design
    note right of Requirements: ...
    Design --> Implementation
    note right of Design: ...
    Implementation --> Testing
    note right of Implementation: ...
    Testing --> Deployment
    note right of Testing: ...
    note right of Deployment: ...
